package EX05;

public class Main {
    /* MÉTODO ESTA NA CLASSE ARVBINBUSCA ABAIXO DO COMENTARIO "EX05".
       NAO CONSEGUI PENSAR NUMA MAIN.

       A COMPLEXIDADE DO METODO OBTEMANCESTRALCOMUM É, NO PIOR CASO O(N).
       SENDO 'N'O NUMERO DE ELEMENTOS DA ARVORE.
     */
}
